[ammo9mm]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 1.0

[ammodefault]
#Set to `false` to remove the item from the game.
enabled = false
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[ammo45acp]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 1.5

[ammo46]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 1.5

[ammo357]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.3

[ammo57]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 2.0

[ammo50ae]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 6.0

[ammo545]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 2.5

[ammo556]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 2.5

[ammo68]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 3.0

[ammo762]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 3.5

[ammo762x51]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 3.5

[ammo338lapua]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 8.0

[ammo50bmg]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 20.0

[ammo12gauge]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 0.2

[ammolasercharge]
#Set to `false` to remove the item from the game.
enabled = false
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[ammocreative]
#Set to `false` to remove the item from the game.
enabled = false
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[grenade40mm]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 2.5

[grenade20mm]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 2.0

[smaw_rocket]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[at4_rocket]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[javelin_rocket]
#Set to `false` to remove the item from the game.
enabled = false
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[grenade]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[m1911a1]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 1.5

[tti_viper]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 1.5

[p30l]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 1.0

[mk23]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 1.5

[glock17]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 1.0

[glock18]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 1.0

[m9]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 1.0

[deserteagle]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 6.0

[rhino]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.3

[m4a1]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 2.5

[m4a1mod1]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 2.5

[ar57]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 2.0

[ro635]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 1.5

[star15]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 3.5

[m4sopmodii]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 2.5

[m16a1]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 2.5

[hk416]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 2.5

[scarl]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 2.5

[xm7]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 3.0

[xm29]
#Set to `false` to remove the item from the game.
enabled = false
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[g36c]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 2.5

[g36k]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 2.5

[sl8]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[mk14ebr]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 3.5

[uar10]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 6.5

[ak47]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 3.5

[ak74]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 2.5

[ak12]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 2.5

[an94]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 2.5

[aug]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 2.5

[aughbar]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 2.5

[mp5]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 1.0

[mp7]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 1.5

[ump45]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 1.5

[vector]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 1.0

[p90]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 2.2

[tmp]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 1.0

[m950]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 1.0

[g41]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 2.5

[g3]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 3.5

[wa2000]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 8.0

[xm3]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 8.0

[c14]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 8.0

[l96a1]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 10.0

[ballista]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 10.0

[gm6lynx]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 20.0

[m590]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 0.63

[m870]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 0.62

[spas12]
#Set to `false` to remove the item from the game.
enabled = false
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 0.2

[m1014]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 0.59

[aa12]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 0.52

[citoricxs]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 0.6

[hs12]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 0.6

[lamg]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 2.5

[mk48]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 3.5

[m249]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 2.5

[m32mgl]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 2.5

[smaw]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[javelin]
#Set to `false` to remove the item from the game.
enabled = false
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[at4]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[m134minigun]
#Set to `false` to remove the item from the game.
enabled = false
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

